- name: Set up SSH security configuration
  when:
    - ansible_os_family == "RedHat"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "PermitEmptyPasswords", value: "no" }
  notify:
    - Restart SSH service RHEL based
    - Restart SSH service Debian based
